### ISSUE TITLE
Stop spawning remote creeps for remotes that are enemy reserved

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#30]
![image](https://user-images.githubusercontent.com/48334001/173251633-0b3945fa-5483-4a75-a162-d2675e396ddb.png)

**Comment by CarsonBurke** [comment]
To clarify, the spawning of remoteCoreAttackers and remoteDefenders should not be limited

**Comment by DefaultO** [comment]
All needs are set to 0 by default, now, in theory. Only if conditional applicable does their value gets increased. The logic of the plan to send Antifa to enemy-owned rooms and edge cases for the reservation part is still missing.

Most code hasn't changed. Rather restructured to check for enemy influence over the room, first, and if it isn't owned and reserved by an enemy, and no enemies are present, harvesters, haulers, dismantlers, and reservers get sent to the room.

The check for if the room is undefined was rather deep down. If that had a reason. Please let me know.

## TODO:
- [x] Stop spawning remote creeps for remotes that are enemy reserved
- [ ] Add further logic to enemy reserved rooms
- [ ] Potential rework, restructuring, and refactoring, once changes are discussed in the Discord Server
- [ ] Testing & Debugging
